image: Visual Studio 2017

install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe

before_build:
- cmd: nuget restore

build:
  project: Thrifty.sln
  verbosity: minimal

test_script:
 - cmd: >-
     dotnet test src\tests\Thrifty.UnitTests & dotnet test src\tests\Thrifty.IntegrationTests